sudo: true
dist: trusty
language:
  - generic
cache:
  - apt

jobs:
  include:
    - stage: dependencies
    - script: ./install-dependencies.sh
    - stage: osg_and_fcl
    - script: ./install-osg.sh
    - script: ./install-fcl.sh
    - stage: openrave
    - script: ./install-openrave.sh
