sudo: true

dist: xenial

language:
  - generic

cache:
  - apt

services:
  - docker

env:
  global:
    - CONTAINER_NAME="ubuntu-cnt"
    - SH="docker exec -t ${CONTAINER_NAME} /bin/bash -c"
  matrix:
    - INFO="OpenSceneGraph-14.04" UVERSION=14.04 COMMAND="./install-osg.sh"
    - INFO="OpenSceneGraph-16.04" UVERSION=16.04 COMMAND="./install-osg.sh"
    - INFO="OpenSceneGraph-18.04" UVERSION=18.04 COMMAND="./install-osg.sh"
    - INFO="OpenRAVE-14.04" UVERSION=14.04 COMMAND="./install-fcl.sh; ./install-openrave.sh"
    - INFO="OpenRAVE-16.04" UVERSION=16.04 COMMAND="./install-fcl.sh; ./install-openrave.sh"
    - INFO="OpenRAVE-18.04" UVERSION=18.04 COMMAND="./install-fcl.sh; ./install-openrave.sh"

before_install:
  - docker run -d --name ${CONTAINER_NAME} -v $(pwd):/travis -w /travis ubuntu:${UVERSION} tail -f /dev/null

install:
  - ${SH} "rm -rf /var/lib/apt/lists/*"
  - ${SH} "apt-get update"
  - ${SH} "apt-get install -y --no-install-recommends lsb-release sudo"

script:
  - ${SH} "./install-dependencies.sh"
  - travis_wait 30 ${SH} "${COMMAND}" > /dev/null
