sudo: true

dist: xenial

language:
  - generic

cache:
  - apt

services:
  - docker

env:
  global:
    - CONTAINER_NAME="ubuntu-cnt"
    - SH="docker exec -t ${CONTAINER_NAME} /bin/bash -c"
  matrix:
    - INFO="OpenSceneGraph-14.04" UDISTRO=trusty COMMAND="./install-osg.sh &> osg.log"
    - INFO="OpenSceneGraph-16.04" UDISTRO=xenial COMMAND="./install-osg.sh &> osg.log"
    - INFO="OpenSceneGraph-18.04" UDISTRO=bionic COMMAND="./install-osg.sh &> osg.log"
    - INFO="OpenRAVE-14.04" UDISTRO=trusty COMMAND="./install-fcl.sh &> fcl.log ; ./install-openrave.sh &> rave.log"
    - INFO="OpenRAVE-16.04" UDISTRO=xenial COMMAND="./install-fcl.sh &> fcl.log ; ./install-openrave.sh &> rave.log"
    - INFO="OpenRAVE-18.04" UDISTRO=bionic COMMAND="./install-fcl.sh &> fcl.log ; ./install-openrave.sh &> rave.log"

before_install:
  - docker run -d --name ${CONTAINER_NAME} --env DEBIAN_FRONTEND=noninteractive -v $(pwd):/travis -w /travis fsuarez6/openrave-dependencies-${UDISTRO}:latest tail -f /dev/null

script:
  - ${SH} "touch osg.log fcl.log rave.log"
  # Output something every minute or Travis kills the job
  - while sleep 1m; do echo "=====[ Installing ${INFO}... ]====="; done &
  - ${SH} "${COMMAND}"
  # Killing background sleep loop
  - kill %1
  - ${SH} "tail -n 50 osg.log"
  - ${SH} "tail -n 50 fcl.log"
  - ${SH} "tail -n 50 rave.log"
